theme: jekyll-theme-Midnight
title: Writing for Future

show_downloads: [false]


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
